name = "DynamicDecisionNetworks"
uuid = "e6e02f22-efc9-48f3-bca6-1c46977dd629"
authors = ["Zachary Sunberg <sunbergzach@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
